# Site settings
title: Caz Brunnen
description: Web Developer
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Caz Brunnen
user_description: I'm an experienced junior developer based in Sydney with an interest in creative projects and emerging technologies. I have over a year's agency experience and am excited to find my next opportunity in web development.
user_title: Front-end Developer
email: cazbrunnen@gmail.com
twitter_username: _hashbang
github_username:  cjbrunnen
linkedin_username: cazbrunnen

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
