# Site settings
title: Caz Brunnen
description: Web Developer
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: http://cazbrunnen.com

# User settings
username: Caz Brunnen
user_description: 
user_title: Front-end Developer
# email: 
twitter_username: cazgotsoul
github_username:  cjbrunnen
linkedin_username: cazbrunnen

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
